### Sumário

1. [Introdução](#1.-Introdução)
2. [Vetores](#2.-Vetores)
3. [Matrizes](#3.-Matrizes)
4. [Espaços Vetoriais](#4.-Espaços-Vetoriais)
5. [Norma](#5.-Norma)
6. [Independência linear](#6.-Independência-linear)
7. [Base e dimensão](#7.-Base-e-dimensão)
8. [Projeção](#8.-Projeção)
9. [Coeficientes de Fourier](#9.-Coeficientes-de-Fourier)
10. [Tipos de espaços](#10.-Tipos-de-espaços)
11. [Combinação linear](#11.-Combinação-linear)

# 1. Introdução

A álgebra linear pode ser vista como uma combinação de álgebra e geometria com uma grande variedade de aplicações, e diversos problemas na ciência e na matemática envolvem a solução de conjuntos de equações lineares. Por exemplo, suponha que você resolveu um sistema de equações lineares e encontrou x = 1 e y = 3. Você pode ver esse resultado como um ponto no plano (x, y), mas uma interpretação geométrica é que como duas equações lineares representam duas retas, a solução representa o ponto de intersecção entre as mesmas. Essa visão nos ajuda a entender casos em que não há solução para o problema (duas retas paralelas) e casos onde há infinitas soluções (ambas equações representam a mesma reta).

Na área de análise e processamento de sinais, os conceitos de vetores, matrizes, espaços vetoriais, base e dimensão são fundamentais para a compreensão da representação dos sinais no domínio da frequência.

Vamos para a segunda revisão!

# 2. Vetores

Um vetor é um arranjo de elementos em uma linha ou coluna, sendo chamado vetor-linha ou vetor-coluna, respectivamente. Vamos representar vetores com uma letra romana (A, B, C, etc) em negrito (e.g. $\mathbf{A}$), mas ao escrever no papel você pode utilizar uma seta em cima da letra (e.g. $\vec{A}$) para indicar que se trata de um vetor. O número de elementos do vetor define a sua dimensão.

**Exemplo 1** <p style="text-align:center">$\mathbf{A} = 
	\begin{bmatrix} 
		a_{1} \\ 
		a_{2} \\ 
		\vdots \\
        a_{n}
	\end{bmatrix}_{nx1} $</p>

<p style="text-align:center">$\mathbf{B} =
	\begin{bmatrix} 
		b_{1} && b_{2} && \dots && b_{n}\\ 
	\end{bmatrix}_{1xn}$</p>

Usamos a letra T para representar a transposta de um vetor:

<p style="text-align:center">$\mathbf{A} =
	\begin{bmatrix} 
		a_{1} \\ 
		a_{2} \\ 
		\vdots \\
        a_{n}
	\end{bmatrix}; \mathbf{A}^{T} = \begin{bmatrix} 
		a_{1} && a_{2} && \dots && a_{n} \\ \end{bmatrix} $</p>


## 2.1 Operações com vetores

### 2.1.1 Adição

A soma entre vetores requer que os mesmos possuam a mesma dimensão e é feita componente a componente: $\mathbf{A}+\mathbf{B} = [a_{i}+b_{i}] = \mathbf{C} = [c_{i}]$. As propriedades comutativa e associativa da adição são válidas para vetores:

<p style="text-align:center">$\mathbf{A}+\mathbf{B} = \mathbf{B}+\mathbf{A}$</p>
<p style="text-align:center">$(\mathbf{A}+\mathbf{B})+\mathbf{C} = (\mathbf{A}+\mathbf{B})+\mathbf{C}$</p>

Dessa forma, parece razoável usar o símbolo $3\mathbf{A}$ para representar a soma $\mathbf{A}+\mathbf{A}+\mathbf{A}$, ou de forma mais geral $c\mathbf{A}$, onde c é um número inteiro, definindo portanto a multiplicação por escalar como $\mathbf{B} = c\mathbf{A} = [ka_{i}]$.

### 2.1.2 Multiplicação

Há dois tipos de multiplicação entre vetores: o primeiro tipo, chamado produto interno (ou escalar), resulta em um escalar, e o segundo tipo, chamado produto vetorial (ou externo), produz um vetor.

#### 2.1.2.1 Produto interno

Sejam $\mathbf{A}$ e $\mathbf{B}$ dois vetores de dimensão (nx1). O produto interno $\mathbf{A} \cdot \mathbf{B}$ entre eles é dado por:

<p style="text-align:center">$\mathbf{A} \cdot \mathbf{B} = \sum_{i=1}^{n}a_{i}b_{i}$</p>

Dois vetores são **ortogonais** quando o produto interno entre eles for igual a zero. Outra maneira de definir o produto interno entre $\mathbf{A}$ e $\mathbf{B}$ é por meio do produto entre a magnitude de $\mathbf{A}$ (ver próxima seção), a magnitude de $\mathbf{B}$ e o cosseno do ângulo entre eles:

<p style="text-align:center">$\mathbf{A} \cdot \mathbf{B} = |\mathbf{A}| |\mathbf{B}|cos(\theta)$</p>

A combinação entre as duas formulações permite encontrar o ângulo entre os vetores.

#### 2.1.2.2 Magnitude (norma) de um vetor

A magnitude de um vetor indica o comprimento da seta no seu gráfico, e a magnitude de um vetor $\mathbf{A}$ é representada por A, |A| ou ||A|| (este último é usado para representar a norma). Pelo teorema de Pitágoras em uma representação 2D, temos:

<p style="text-align:center">$A = ||\mathbf{A}|| = \sqrt{A_{x}^{2}+A_{y}^{2}}$</p>

De forma mais geral para espaços de dimensões maiores, a magnitude de um vetor é dada pela raíz quadrada do produto interno dele com ele mesmo:

<p style="text-align:center">$A = ||\mathbf{A}|| = \sqrt{\mathbf{A}^{T}\mathbf{A}}$</p>

Um vetor de magnitude igual a 1 é chamado de vetor unitário. Para qualquer $\mathbf{A} \neq 0$, $\mathbf{A}/|\mathbf{A}|$ é um vetor unitário.

#### 2.1.2.3 Propriedades do produto escalar

Sejam $\mathbf{X}$, $\mathbf{Y}$ e $\mathbf{Z}$ vetores de $\mathbb{R}^n$ e $\alpha$ um escalar.

1. $\mathbf{X} \cdot \mathbf{Y} = \mathbf{Y} \cdot \mathbf{X}$ (comutatividade)
2. $\mathbf{X} \cdot (\mathbf{Y}+\mathbf{Z}) = \mathbf{X} \cdot \mathbf{Y} + \mathbf{X} \cdot \mathbf{Z}$ (distribuição em relação a soma)
3. $(\alpha \mathbf{X}) \cdot \mathbf{Y} = \alpha (\mathbf{X} \cdot \mathbf{Y}) = \mathbf{X} \cdot \alpha\mathbf{Y}$
4. $| \mathbf{X} \cdot \mathbf{Y} | \le |\mathbf{X}| |\mathbf{Y}|$ (Desigualdade de Cauchy-Schwarz)
5. $| \mathbf{X} + \mathbf{Y} | \le |\mathbf{X}| + |\mathbf{Y}|$

#### 2.1.2.4 Produto vetorial

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

## 2.2 Vetores em Python

A forma mais prática de representar vetores (e matrizes) em Python é utilizando objetos ``array`` da biblioteca Numpy. As operações entre vetores são feitas de forma muito simples.

In [1]:
# Vamos importar a biblioteca e inicializar alguns vetores para testar
import numpy as np

a = np.array([1, 4, 5])
b = np.array([4, 7, 2])

In [2]:
type(a)

numpy.ndarray

In [3]:
a.shape

(3,)

In [4]:
# soma
a + b

array([ 5, 11,  7])

In [5]:
# existem diversas maneiras de obter a magnitude de um vetor em Python

# uma maneira não muito prática é iterando pelos elementos do vetor
s = 0
for elemento in a:
    s += elemento**2
print("Magnitude usando iteração: ", s**0.5)

# podemos usar a função dot do numpy para calcular o produto interno de a
# com ele mesmo e tirar a raíz quadrada
print("Magnitude usando np.dot: ",np.sqrt(np.dot(a,a)))

# podemos usar a função norm da biblioteca de álgebra linear do numpy
from numpy.linalg import norm

print("Magnitude usando a função norm: ",norm(a))

# se não quisermos importar nada, uma forma simples é usando o operador @,
# que calcula o produto interno

print("Magnitude usando o @: ",(a@a)**0.5)

Magnitude usando iteração:  6.48074069840786
Magnitude usando np.dot:  6.48074069840786
Magnitude usando a função norm:  6.48074069840786
Magnitude usando o @:  6.48074069840786


O produto vetorial pode ser obtido facilmente por meio da função `cross` do Numpy, para vetores de dimensões 2 ou 3.

In [6]:
print(np.cross(a, b))

# Repare que a x b = -b x a
print(np.cross(-b, a))

[-27  18  -9]
[-27  18  -9]


**Exercícios.** Resolva:

<p style="text-align:center">$ 
	\begin{bmatrix} 
		-1 & 3 & -5 &2
	\end{bmatrix} + 
    	\begin{bmatrix} 
		-1 & 2 & 4 & 2
	\end{bmatrix} = 
    $</p>

Calcule o produto interno entre $
	a = \begin{bmatrix} 
		-1 & 3 & -5 & 2\\ 
	\end{bmatrix} , 
    	b = \begin{bmatrix} 
		3 & 2 & -1 & 2\\
	\end{bmatrix} $

Calcule o produto externo entre $ 
	a = \begin{bmatrix} 
		-1 & 3 & -5\\ 
	\end{bmatrix} , 
    	b = \begin{bmatrix} 
		3 & 2 & -1\\
	\end{bmatrix}$

# 3. Matrizes

Uma matriz é um arranjo retangular de números, onde uma matriz $A_{mxn}$ (m por n) é essencialmente uma tabela de mn números dispostos em m linhas e n colunas.

<p style="text-align:center">$\mathbf{A} =
	\begin{bmatrix} 
		x_{11} & x_{12} & \dots & x_{1n} \\ 
		x_{21} & x_{22} & \dots & x_{2n}  \\ 
		\vdots & \vdots & \vdots & \vdots \\
        x_{m1} & x_{m2} & \dots & x_{mn} \\
	\end{bmatrix} $</p>

Usamos a notação $A = (a_{ij})$ para descrever o elemento na i-ésima linha e j-ésima coluna da matriz. Se m = n, então A é uma matriz quadrada de ordem n e os elementos $a_{11}, a_{22}, ..., a_{nn}$ formam a diagonal principal de A. Matriz com uma linha ou coluna é denominada matriz linha ou coluna, respectivamente.

## 3.1 Redução por linhas e posto de matriz

Considere o seguinte conjunto de equações:

 $\begin{cases}
      2x -z = 2\\
      6x + 5y + 3z = 7 \\
      2x -y  = 4
    \end{cases}\,$
    
Nós podemos representar todas as informações essenciais do conjunto de equações em uma matriz chamada **aumentada**, onde as primeiras colunas são os coeficientes no lado esquerdo da igualdade e a última coluna é igual aos valores do lado direito da igualdade:

<p style="text-align:center">$\mathbf{A} =  
	\begin{bmatrix} 
		2 & 0 & -1 & 2 \\ 
		6 & 5 & 3 & 7  \\ 
		2 & -1 & 0 & 4 \\
	\end{bmatrix} $</p>

Com a forma matricial não precisamos escrever todo o conjunto de equações e podemos trabalhar com um processo chamado **redução por linhas**, que é o modo como o computador resolver sistemas lineares de equações.

1. Primeiramente vamos usar a primeira linha para eliminar os termos x da segunda e terceira linhas. Para tanto, vamos fazer $L_{2}-3L_{1}$ e $L_{2}-L_{1}$, onde L representa a linha:

<p style="text-align:center">$ 
	\begin{bmatrix} 
		2 & 0 & -1 & 2 \\ 
		0 & 5 & 6 & 1  \\ 
		0 & -1 & 1 & 2 \\
	\end{bmatrix}
 $</p>

2. Trocaremos a segunda e a terceira linha de posição:

<p style="text-align:center">$
	\begin{bmatrix} 
		2 & 0 & -1 & 2 \\ 
        0 & -1 & 1 & 2 \\
		0 & 5 & 6 & 1  \\ 
	\end{bmatrix}
 $</p>

3. $L_{3}+5L{1}$:

<p style="text-align:center">$ 
	\begin{bmatrix} 
		2 & 0 & -1 & 2 \\ 
        0 & -1 & 1 & 2 \\
		0 & 0 & 11 & 11  \\ 
	\end{bmatrix}
 $</p>

4. Dividiremos a linha 3 por 11 e a usaremos para simplificar as outras linhas:

<p style="text-align:center">$
	\begin{bmatrix} 
		2 & 0 & 0 & 3 \\ 
        0 & -1 & 0 & 1 \\
		0 & 0 & 1 & 1  \\ 
	\end{bmatrix}
 $</p>

5. A matriz reduzida por linha é:

<p style="text-align:center">$
	\begin{bmatrix} 
		1 & 0 & 0 & 3/2 \\ 
        0 & 1 & 0 & -1 \\
		0 & 0 & 1 & 1  \\ 
	\end{bmatrix}
 $</p>

Logo, a solução do sistema de equações lineares é x = 3/2, y = -1 e z = 1. Ao realizar a redução por linhas, as operações permitidas são: (i) trocar duas linhas; (ii) multiplicar (ou dividir) uma linha por uma constante diferente de zero e (iii) adicionar ou subtrair o múltiplo de uma linha a outra.

**Exercício.** Reduza por linhas (na mão!) o seguinte sistema de equações:

 $\begin{cases}
      x - y + 4z = 5\\
      2x - 3y + 8z = 4 \\
      x -2y + 4z = 9
    \end{cases}\,$
    
Se você chegou em $ 
	\begin{bmatrix} 
		1 & 0 & 4 & 11 \\ 
        0 & -1 & 0 & -6 \\
		0 & 0 & 0 & 20  \\ 
	\end{bmatrix}$, pode parar. Aqui, a terceira linha diz que 0z = 20, o que não é verdade para nenhum valor finito de z. Dizemos que o sistema é **inconsistente** e que não há solução. POSTO